---
- name: instal apche on ubuntu servers
  hosts: ubuntu
  become: yes
  tasks:

  - name: update respostry index
    apt:
      update_cache: yes

  - name: install apache2 package 
    apt:
      name: apache2
      state: latest

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest

