---
- name: remove apche on ubuntu servers
  hosts: ubuntu
  become: yes
  tasks:

  - name: update respostry index
    apt:
      update_cache: yes

  - name: Remove apache2 package 
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache2
    apt:
      name: libapache2-mod-php
      state: absent

